# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

CMakeFiles/boo.dir/main.cpp.o: \
 /home/aadithya/Desktop/codebin/fastfetch/build/CMakeFiles/_CMakeLTOTest-CXX/src/main.cpp
